# Generated by Django 4.0.3 on 2022-03-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=0, verbose_name='Тест публикации'),
            preserve_default=False,
        ),
    ]
