# Generated by Django 4.0.3 on 2022-03-21 15:56

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, validators=[posts.models.validate_summary], verbose_name='Текст на главной'),
        ),
    ]
