# Generated by Django 4.0.3 on 2022-03-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='test_photos', verbose_name='Обложка теста'),
        ),
    ]
